export const categories = [
    {
        id: 1,
        name: 'Pizza',
        image: require('../assets/images/pizzaIcon.png'),
    },
    {
        id: 2,
        name: 'Burger',
        image: require('../assets/images/burger.png'),
    },
    {
        id: 3,
        name: 'Kota',
        image: require('../assets/images/kota.png'),
    },
    {
        id: 4,
        name: 'Chinese',
        image: require('../assets/images/pizzaIcon.png'),
    },
    {
        id: 5,
        name: 'Noodles',
        image: require('../assets/images/noodles.png'),
    },
    {
        id: 6,
        name: 'Grills',
        image: require('../assets/images/grills.png'),
    },

]


export const featured = [
  {
    id: 1,
    title: "Hot and Spicy",
    description: "soft and tender fried chicken",
    specialty: "Chicken",
    restaurants: [
      {
        id: 1,
        name: "Bobby Chicken Tikka",
        image: require("../assets/images/pizza.png"),
        description: "Hot and spicy pizzas",
        lng: -85.5324269,
        lat: 38.2145602,
        address: "434 second street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
          {
            id: 2,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
          {
            id: 3,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
        ],
      },
      {
        id: 2,
        name: "Papa Johns",
        image: require("../assets/images/pizza.png"),
        description: "Hot and spicy pizzas",
        lng: -85.5324269,
        lat: 38.2145602,
        address: "434 second street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
          {
            id: 2,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
          {
            id: 3,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
        ],
      },
      {
        id: 3,
        name: "Kasi Chicken Dust",
        image: require("../assets/images/pizza.png"),
        description: "Hot and spicy pizzas",
        lng: -85.5324269,
        lat: 38.2145602,
        address: "434 second street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
          {
            id: 2,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
          {
            id: 3,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
        ],
      },
    ],
  },
  {
    id: 2,
    title: "Bobby Chicken Tikka",
    description: "Grilled Chicken",
    specialty: "Chicken",
    restaurants: [
      {
        id: 1,
        name: "Bobby Chicken Tikka",
        image: require("../assets/images/pizza.png"),
        description: "Hot and spicy pizzas",
        lat: -26.6212857,
        lng: 27.9390072,
        address: "19 Andesite Ave, Waldrift",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
          {
            id: 2,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
          {
            id: 3,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
        ],
      },
      {
        id: 2,
        name: "Papa Johns",
        image: require("../assets/images/pizza.png"),
        description: "Hot and spicy pizzas",
        lng: -85.5324269,
        lat: 38.2145602,
        address: "434 second street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        specialty: "Burgers",
        dishes: [
          {
            id: 1,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
          {
            id: 2,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
          {
            id: 3,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
        ],
      },
      {
        id: 3,
        name: "Kasi Chicken Dust",
        image: require("../assets/images/pizza.png"),
        description: "Hot and spicy pizzas",
        lng: -85.5324269,
        lat: 38.2145602,
        address: "434 second street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        specialty: "Chicken",
        dishes: [
          {
            id: 1,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
          {
            id: 2,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
          {
            id: 3,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
        ],
      },
    ],
  },
  {
    id: 3,
    title: "Mamas Kitchen",
    description: "Home made South African dishes",
    specialty: "Meals",
    restaurants: [
      {
        id: 1,
        name: "Bobby Chicken Tikka",
        image: require("../assets/images/pizza.png"),
        description: "Hot and spicy pizzas",
        lng: -85.5324269,
        lat: 38.2145602,
        address: "434 second street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
          {
            id: 2,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
          {
            id: 3,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
        ],
      },
      {
        id: 2,
        name: "Papa Johns",
        image: require("../assets/images/pizza.png"),
        description: "Hot and spicy pizzas",
        lng: -85.5324269,
        lat: 38.2145602,
        address: "434 second street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        specialty: "Burgers",
        dishes: [
          {
            id: 1,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
          {
            id: 2,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
          {
            id: 3,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
        ],
      },
      {
        id: 3,
        name: "Kasi Chicken Dust",
        image: require("../assets/images/pizza.png"),
        description: "Hot and spicy pizzas",
        lng: -85.5324269,
        lat: 38.2145602,
        address: "434 second street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        specialty: "Chicken",
        dishes: [
          {
            id: 1,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
          {
            id: 2,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
          {
            id: 3,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
        ],
      },
    ],
  },
];
